### PR TITLE
ST-151-feature/AccountCreation

### PR DESCRIPTION
**Pull request by YoonseoPark0518**
PR for ST-151

### CODE REVIEW

**Review by Blackkirby72 — COMMENTED** [review]
I'll leave it to someone more familiar with front end work to actually approve the PR

**Comment by YoonseoPark0518** [comment]
Please review it

**Comment by YoonseoPark0518** [comment]
Please review this

**Review by KarstenRoland — APPROVED** [review]
Looks great, let's do this

**Pull request merged**
